import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, theme } from "antd";

export const metadata: Metadata = {
  title: "发布页面",
  description: "Generated by create next app",
};

const releaseAntdTheme = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: "var(--ide-accent)",
    colorBgContainer: "var(--ide-control-bg)",
    colorBgLayout: "var(--ide-bg)",
    colorBorder: "var(--ide-border)",
    colorText: "var(--ide-text)",
    colorTextSecondary: "var(--ide-text-muted)",
    colorFillSecondary: "var(--ide-hover)",
    borderRadius: 2,
    fontSize: 13,
  },
  components: {
    Button: {
      borderRadius: 2,
      controlHeight: 28,
      defaultBg: "var(--ide-control-bg)",
      defaultBorderColor: "var(--ide-control-border)",
      defaultColor: "var(--ide-text)",
    },
    Layout: {
      bodyBg: "var(--ide-bg)",
      siderBg: "var(--ide-sidebar-bg)",
    },
    Tabs: {
      itemColor: "var(--ide-text-muted)",
      itemSelectedColor: "var(--ide-text)",
      itemHoverColor: "var(--ide-text)",
      cardBg: "var(--ide-header-bg)",
    },
    Input: {
      activeBorderColor: "var(--ide-accent)",
      hoverBorderColor: "var(--ide-accent)",
    },
    InputNumber: {
      activeBorderColor: "var(--ide-accent)",
      hoverBorderColor: "var(--ide-accent)",
    },
    Switch: {
      colorPrimary: "var(--ide-accent)",
      colorPrimaryHover: "var(--ide-accent)",
    },
  },
} as const;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="release-root h-full w-full overflow-hidden">
        <AntdRegistry>
          <ConfigProvider theme={releaseAntdTheme}>{children}</ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
